### ISSUE TITLE
Expand Coiled deployment documentation

### ISSUE THREAD

**Issue by jrbourbeau** [rapidsai/deployment#186]
I was chatting with @jacobtomlinson and @mmccarty today and Jacob mentioned that the [current Coiled deployment docs here](https://github.com/rapidsai/deployment/blob/5ebd97cb99534b4d6708b2307bdb97652fdd3150/source/platforms/coiled.md) are pretty minimal and that it would be nice to have a bit more content here. @jacobtomlinson what do you think makes sense to include here? 

cc @ntabris, from the Coiled side, for what you think might make sense to include here too 

Also, just an FYI @ntabris has been working to make gpu-enabled software environments a better experience on Coiled and I think there are also plans to update the gpu documentation in https://docs.coiled.io

**Comment by ntabris** [comment]
> Maybe we should have a similar quickstart section before linking off to Coiled's docs for more detailed deployment info.

That makes sense to me.

> I don't really want to include much about managing Coiled environments in the RAPIDS docs, especially while package sync and environment creation doesn't play nicely with cudatoolkit.

Samantha recently added support (not yet released) for setting CUDA version when building software environment, and I've been trying this in staging. I was able to create a software environment with RAPIDS + Optuna and was able to run the Optuna XGBoost example notebook with very minimal changes (i.e., get the right client, and use that to get n workers).

I'll follow up on this issue when we're released that, since it should make it easier to run examples.

**Comment by ntabris** [comment]
We've just released the update that lets you create software environment with CUDA packages. It's slow (these are big!), @shughes-uk is working on making it fast, but working slowly is nicer than not working.

(This needs `coiled>=0.5.6` which is on pypi but not yet on conda-forge.)

There's a pretty minimal example in our GPU doc: https://docs.coiled.io/user_guide/gpu.html#example-gpu-conda-environment

That example software env lets you use this example notebook: https://github.com/rapidsai/deployment/blob/main/source/examples/xgboost-gpu-hpo-job-parallel-k8s/notebook.ipynb

On that notebook, skip cells 1-4, change 5 to

```
from dask.distributed import Client

client = Client()
n_workers = len(client.scheduler_info()["workers"])
```

and everything runs fine from there!

![image](https://user-images.githubusercontent.com/46289310/226741206-6e895d0d-bca6-4c57-aa18-2175957fcd53.png)

**Comment by jacobtomlinson** [comment]
Sweet! Thanks for the effort @ntabris @shughes-uk

**Comment by jacobtomlinson** [comment]
I started working on #189 but was running into errors when starting the cluster so wanted to get some feedback before I continue.

I created a cluster like this

```python
import coiled

coiled.create_software_environment(
    name="rapids-23-04-nightly-conda",
    account="dask",
    gpu_enabled=True,  # sets CUDA version for Conda to ensure GPU version of packages get installed
    conda={
        "channels": ['rapidsai-nightly', 'conda-forge', 'nvidia'],
        "dependencies": ['rapids=23.04', 'python=3.10', 'cudatoolkit=11.5']
    },
)

cluster = coiled.Cluster(
    account="dask",
    software="rapids-23-04-nightly-conda",  # specify the software env you just created
    jupyter=True,  # run Jupyter server on scheduler
    scheduler_gpu=True,  # add GPU to scheduler
    n_workers=4,
    worker_gpu=1,  # single T4 per worker
    worker_class="dask_cuda.CUDAWorker",  # recommended
)

print(cluster.jupyter_link)
```

The cluster seems to start ok but the Jupyter link gives a 404 and when checking the cluster logs I'm seeing a lot of:

```
2023-03-22 11:07:57Z
distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
Unable to start CUDA Context
Traceback (most recent call last):
  File "/opt/coiled/env/lib/python3.10/site-packages/dask_cuda/initialize.py", line 31, in _create_cuda_context
    distributed.comm.ucx.init_once()
  File "/opt/coiled/env/lib/python3.10/site-packages/distributed/comm/ucx.py", line 153, in init_once
    import ucp as _ucp
  File "/opt/coiled/env/lib/python3.10/site-packages/ucp/__init__.py", line 19, in <module>
    from .core import *  # noqa
  File "/opt/coiled/env/lib/python3.10/site-packages/ucp/core.py", line 16, in <module>
    from . import comm
  File "/opt/coiled/env/lib/python3.10/site-packages/ucp/comm.py", line 8, in <module>
    from ._libs import arr, ucx_api
ImportError: libnuma.so.1: cannot open shared object file: No such file or directory
```

Cluster was https://cloud.coiled.io/clusters/173861/overview?account=dask&tab=Logs is that's helpful for debugging on your end.

**Comment by jacobtomlinson** [comment]
Looks like that error was a packaging issue on our side. @pentschev talked me through a workaround. I needed to install `libnuma` in the conda env. A PR is open to fix this dependency though so I don't think we need to worry about documenting it.

```python
coiled.create_software_environment(
    name="rapids-23-04-nightly-conda",
    account="dask",
    gpu_enabled=True,  # sets CUDA version for Conda to ensure GPU version of packages get installed
    conda={
        "channels": ['rapidsai-nightly', 'conda-forge', 'nvidia'],
        "dependencies": ['rapids=23.04', 'python=3.10', 'cudatoolkit=11.5', 'libnuma']
    },
)
```


That error is now gone from the logs but I'm still not getting Jupyter.

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/1610850/226928694-7e81edfe-6aed-4fd8-bd79-3a6d9618b027.png">

https://cloud.coiled.io/clusters/174193/overview?account=dask&tab=Logs

**Comment by ntabris** [comment]
> Going to try again with the Jupyter dependency but would be nice if there was some error handling around this

Totally agree, there's definitely a lot of polish needed around the Jupyter feature. (I'll open an issue internally about this specific thing.)
